import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '10mb' }));

  // API endpoints FIRST
  app.post("/api/tts", async (req: any, res: any) => {
    try {
      const { text, voice = "Kore", voiceStyle, pace, emphasis, pauses } = req.body;

      if (!text) {
        return res.status(400).json({ error: "Text is required" });
      }

      if (!process.env.GEMINI_API_KEY) {
        return res.status(500).json({ error: "GEMINI_API_KEY is not configured in environment variables. Please configure it in Settings > Secrets." });
      }

      const ai = new GoogleGenAI({
        apiKey: process.env.GEMINI_API_KEY,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          }
        }
      });

      // Construct a high-impact prompt for the TTS model to style the reading
      const formattedPrompt = `You are a high-quality, professional text-to-speech engine.
Read the following script exactly as instructed. 

VOICE STYLE INSTRUCTIONS:
- Tone/Style: ${voiceStyle || "Young, confident, energetic. Sound like you are explaining something exciting to a friend, not reading from a textbook."}
- Pace: ${pace || "Speak at a fast but clear pace suitable for a 60-second YouTube Short."}
- Pauses: ${pauses || "Add natural pauses after important points."}
- Emphasis: ${emphasis || "Emphasize words like 'Lower Bound', 'Upper Bound', 'Floor', 'Ceil', 'greater than', and 'greater than or equal to' with enthusiasm."}

SCRIPT TO READ:
${text}`;

      console.log(`Generating speech with voice: ${voice}`);
      const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-tts-preview",
        contents: [{ parts: [{ text: formattedPrompt }] }],
        config: {
          responseModalities: ["AUDIO"],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: voice },
            },
          },
        },
      });

      const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
      if (!base64Audio) {
        return res.status(500).json({ error: "No audio was generated by the Gemini TTS model. Try a different voice or shorter text." });
      }

      // Convert raw 24kHz 16-bit mono PCM into standard WAV
      const pcmBuffer = Buffer.from(base64Audio, "base64");
      const wavBuffer = pcmToWav(pcmBuffer, 24000);
      const base64Wav = wavBuffer.toString("base64");

      res.json({
        audioUrl: `data:audio/wav;base64,${base64Wav}`,
        voice,
        length: pcmBuffer.length
      });
    } catch (err: any) {
      console.error("TTS generation error:", err);
      res.status(500).json({ error: err.message || "An unexpected error occurred during TTS generation." });
    }
  });

  // Helper to convert 24kHz mono 16-bit PCM to standard WAV
  function pcmToWav(pcmBuffer: Buffer, sampleRate: number = 24000): Buffer {
    const wavHeader = Buffer.alloc(44);
    const dataLength = pcmBuffer.length;
    const fileLength = dataLength + 36;

    wavHeader.write("RIFF", 0);
    wavHeader.writeUInt32LE(fileLength, 4);
    wavHeader.write("WAVE", 8);
    wavHeader.write("fmt ", 12);
    wavHeader.writeUInt32LE(16, 16);
    wavHeader.writeUInt16LE(1, 20); // 1 = PCM
    wavHeader.writeUInt16LE(1, 22); // Channels = 1 (mono)
    wavHeader.writeUInt32LE(sampleRate, 24);
    wavHeader.writeUInt32LE(sampleRate * 2, 28); // byte rate = sampleRate * channels * 16 / 8
    wavHeader.writeUInt16LE(2, 32); // block align = channels * 16 / 8
    wavHeader.writeUInt16LE(16, 34); // bits per sample
    wavHeader.write("data", 36);
    wavHeader.writeUInt32LE(dataLength, 40);

    return Buffer.concat([wavHeader, pcmBuffer]);
  }

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req: any, res: any) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
